# Generated by Django 5.0.1 on 2024-06-14 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2024, 6, 14, 5, 29, 5, 240739, tzinfo=datetime.timezone.utc), max_length=150, unique=True, verbose_name='User slug'),
            preserve_default=False,
        ),
    ]
