# Generated by Django 5.0.1 on 2024-06-14 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_blog_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, related_name='viewed_blogs', to=settings.AUTH_USER_MODEL),
        ),
    ]
