# Generated by Django 5.0.1 on 2024-06-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_blog_viewed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=models.TextField(blank=True, verbose_name='Blog text'),
        ),
    ]
